# Generated by Django 4.2.7 on 2023-11-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JejuTouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('road_address', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('postcode', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=255)),
                ('image_description', models.CharField(max_length=255)),
                ('all_tag', models.TextField()),
            ],
        ),
    ]
