# Generated by Django 4.2.7 on 2023-11-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goormthon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jejutouristspot',
            name='all_tag',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jejutouristspot',
            name='image_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jejutouristspot',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jejutouristspot',
            name='introduction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jejutouristspot',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='jejutouristspot',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='jejutouristspot',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jejutouristspot',
            name='postcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jejutouristspot',
            name='road_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jejutouristspot',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
