# Generated by Django 4.2.7 on 2023-12-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goormthon_app', '0002_alter_jejutouristspot_all_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jejutouristspot',
            old_name='image_url',
            new_name='URL',
        ),
        migrations.RenameField(
            model_name='jejutouristspot',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='jejutouristspot',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='jejutouristspot',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='jejutouristspot',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
