# Generated by Django 4.2.7 on 2023-12-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goormthon_app', '0003_rename_image_url_jejutouristspot_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jejutouristspot',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
