# Generated by Django 4.2.7 on 2023-12-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goormthon_app', '0005_rename_url_jejutouristspot_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jejutouristspot',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
